import { PrismaClient } from '../generated';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting comprehensive seed for PARKETSENSE ERP v2.0...');

  // Phase 1A.1: Create all ProductTypes
  const productTypes = [
    {
      id: 'pt_parquet',
      name: 'parquet',
      nameBg: 'Паркет',
      nameEn: 'Parquet',
      icon: '🏠',
      description: 'Естествен паркет, инженерен паркет и ламинат',
      displayOrder: 1,
      isActive: true,
    },
    {
      id: 'pt_doors',
      name: 'doors',
      nameBg: 'Врати',
      nameEn: 'Doors',
      icon: '🚪',
      description: 'Интериорни и входни врати',
      displayOrder: 2,
      isActive: true,
    },
    {
      id: 'pt_furniture',
      name: 'furniture',
      nameBg: 'Мебели',
      nameEn: 'Furniture',
      icon: '🪑',
      description: 'Офис и домашни мебели',
      displayOrder: 3,
      isActive: true,
    },
    {
      id: 'pt_wall_coverings',
      name: 'wall_coverings',
      nameBg: 'Стенни облицовки',
      nameEn: 'Wall Coverings',
      icon: '🧱',
      description: 'Декоративни стенни панели и облицовки',
      displayOrder: 4,
      isActive: true,
    },
    {
      id: 'pt_installation_services',
      name: 'installation_services',
      nameBg: 'Услуги за монтаж',
      nameEn: 'Installation Services',
      icon: '🔧',
      description: 'Професионални услуги за монтаж',
      displayOrder: 5,
      isActive: true,
    },
    {
      id: 'pt_installation_materials',
      name: 'installation_materials',
      nameBg: 'Материали за монтаж',
      nameEn: 'Installation Materials',
      icon: '🛠️',
      description: 'Лепила, подложки и аксесоари за монтаж',
      displayOrder: 6,
      isActive: true,
    },
    {
      id: 'pt_decking_siding',
      name: 'decking_siding',
      nameBg: 'Декинг и сайдинг',
      nameEn: 'Decking & Siding',
      icon: '🏡',
      description: 'Външни настилки и облицовки',
      displayOrder: 7,
      isActive: true,
    },
    {
      id: 'pt_accessories',
      name: 'accessories',
      nameBg: 'Аксесоари',
      nameEn: 'Accessories',
      icon: '📦',
      description: 'Первази, профили и други аксесоари',
      displayOrder: 8,
      isActive: true,
    },
  ];

  console.log('Creating ProductTypes...');
  for (const productType of productTypes) {
    await prisma.productType.upsert({
      where: { id: productType.id },
      update: productType,
      create: productType,
    });
  }

  // Phase 1A.2: Create all Manufacturers
  const manufacturers = [
    // Паркет производители
    {
      id: 'mf_foglie_doro',
      name: 'foglie_doro',
      displayName: "Foglie d'Oro",
      code: 'FOGLIE',
      website: 'https://fogliedor.it',
      description: 'Италианска луксозна марка за паркет',
      colorCode: '#DAA520',
      isActive: true,
    },
    {
      id: 'mf_salis',
      name: 'salis',
      displayName: 'Salis',
      code: 'SALIS',
      website: 'https://salis.it',
      description: 'Италиански производител на висококачествен паркет',
      colorCode: '#8B4513',
      isActive: true,
    },
    {
      id: 'mf_weitzer',
      name: 'weitzer',
      displayName: 'Weitzer',
      code: 'WEITZER',
      website: 'https://weitzer.com',
      description: 'Австрийски производител на премиум паркет',
      colorCode: '#2E8B57',
      isActive: true,
    },
    {
      id: 'mf_friulparchet',
      name: 'friulparchet',
      displayName: 'Friulparchet',
      code: 'FRIULPARCHET',
      website: 'https://friulparchet.it',
      description: 'Итало-словенска компания за инженерен паркет',
      colorCode: '#B22222',
      isActive: true,
    },
    {
      id: 'mf_berti',
      name: 'berti',
      displayName: 'Berti',
      code: 'BERTI',
      website: 'https://berti.net',
      description: 'Италиански лидер в производството на паркет',
      colorCode: '#4169E1',
      isActive: true,
    },
    // Врати
    {
      id: 'mf_bluinterni',
      name: 'bluinterni',
      displayName: 'Bluinterni',
      code: 'BLUINTERNI',
      website: 'https://bluinterni.it',
      description: 'Италиански производител на интериорни врати',
      colorCode: '#00008B',
      isActive: true,
    },
    // Мебели
    {
      id: 'mf_arte_brotto',
      name: 'arte_brotto',
      displayName: 'Arte Brotto',
      code: 'ARTEBROTTO',
      website: 'https://artebrotto.it',
      description: 'Италиански производител на луксозни мебели',
      colorCode: '#8B4513',
      isActive: true,
    },
    {
      id: 'mf_sicis',
      name: 'sicis',
      displayName: 'Sicis',
      code: 'SICIS',
      website: 'https://sicis.com',
      description: 'Итало-словенска компания за декоративни покрития',
      colorCode: '#FFD700',
      isActive: true,
    },
    {
      id: 'mf_talenti',
      name: 'talenti',
      displayName: 'Talenti',
      code: 'TALENTI',
      website: 'https://talentisrl.com',
      description: 'Итало-словенски производител на градински мебели',
      colorCode: '#228B22',
      isActive: true,
    },
    {
      id: 'mf_decastelli',
      name: 'decastelli',
      displayName: 'Decastelli',
      code: 'DECASTELLI',
      website: 'https://decastelli.it',
      description: 'Итало-словенски производител на метални изделия',
      colorCode: '#696969',
      isActive: true,
    },
    // Декинг и други
    {
      id: 'mf_ravaioli',
      name: 'ravaioli',
      displayName: 'Ravaioli',
      code: 'RAVAIOLI',
      website: 'https://ravaioli.it',
      description: 'Итало-словенски производител на декинг',
      colorCode: '#8B4513',
      isActive: true,
    },
    {
      id: 'mf_uzin',
      name: 'uzin',
      displayName: 'Uzin',
      code: 'UZIN',
      website: 'https://uzin-utz.com',
      description: 'Немски производител на лепила и грундове',
      colorCode: '#FF6347',
      isActive: true,
    },
    {
      id: 'mf_parketsense_pro',
      name: 'Паркетсенс ПРО',
      displayName: 'Паркетсенс ПРО',
      code: 'PARKETSENSEPRO',
      website: 'https://parketsense.bg',
      description: 'Собствена марка за професионални решения',
      colorCode: '#006400',
      isActive: true,
    },
  ];

  console.log('Creating Manufacturers...');
  for (const manufacturer of manufacturers) {
    await prisma.manufacturer.upsert({
      where: { id: manufacturer.id },
      update: manufacturer,
      create: manufacturer,
    });
  }

  // Phase 1A.3: Create AttributeTypes for all ProductTypes
  const attributeTypes = [
    // Паркет атрибути
    {
      id: 'at_parquet_wood_type',
      name: 'wood_type',
      nameBg: 'Дървесина',
      nameEn: 'Wood Type',
      type: 'SELECT',
      productTypeId: 'pt_parquet',
      isRequired: true,
      displayOrder: 1,
      icon: '🌳',
    },
    {
      id: 'at_parquet_construction',
      name: 'construction',
      nameBg: 'Тип конструкция',
      nameEn: 'Construction Type',
      type: 'SELECT',
      productTypeId: 'pt_parquet',
      isRequired: true,
      displayOrder: 2,
      icon: '🔨',
    },
    {
      id: 'at_parquet_thickness',
      name: 'thickness',
      nameBg: 'Дебелина',
      nameEn: 'Thickness',
      type: 'SELECT',
      productTypeId: 'pt_parquet',
      isRequired: true,
      displayOrder: 3,
      icon: '📏',
    },
    {
      id: 'at_parquet_width',
      name: 'width',
      nameBg: 'Ширина',
      nameEn: 'Width',
      type: 'SELECT',
      productTypeId: 'pt_parquet',
      isRequired: true,
      displayOrder: 4,
      icon: '↔️',
    },
    {
      id: 'at_parquet_length',
      name: 'length',
      nameBg: 'Дължина',
      nameEn: 'Length',
      type: 'SELECT',
      productTypeId: 'pt_parquet',
      isRequired: true,
      displayOrder: 5,
      icon: '↕️',
    },
    {
      id: 'at_parquet_color',
      name: 'color',
      nameBg: 'Цвят',
      nameEn: 'Color',
      type: 'COLOR',
      productTypeId: 'pt_parquet',
      isRequired: true,
      displayOrder: 6,
      icon: '🎨',
    },
    {
      id: 'at_parquet_finish',
      name: 'finish',
      nameBg: 'Финиш',
      nameEn: 'Finish',
      type: 'SELECT',
      productTypeId: 'pt_parquet',
      isRequired: true,
      displayOrder: 7,
      icon: '✨',
    },
    {
      id: 'at_parquet_selection',
      name: 'selection',
      nameBg: 'Селекция',
      nameEn: 'Selection',
      type: 'SELECT',
      productTypeId: 'pt_parquet',
      isRequired: false,
      displayOrder: 8,
      icon: '🏆',
    },
    {
      id: 'at_parquet_collection',
      name: 'collection',
      nameBg: 'Колекция',
      nameEn: 'Collection',
      type: 'SELECT',
      productTypeId: 'pt_parquet',
      isRequired: false,
      displayOrder: 9,
      icon: '📚',
    },
    // Врати атрибути
    {
      id: 'at_doors_type',
      name: 'door_type',
      nameBg: 'Тип врата',
      nameEn: 'Door Type',
      type: 'SELECT',
      productTypeId: 'pt_doors',
      isRequired: true,
      displayOrder: 1,
      icon: '🚪',
    },
    {
      id: 'at_doors_frame_material',
      name: 'frame_material',
      nameBg: 'Материал каса',
      nameEn: 'Frame Material',
      type: 'SELECT',
      productTypeId: 'pt_doors',
      isRequired: true,
      displayOrder: 2,
      icon: '🪵',
    },
    {
      id: 'at_doors_finish_push',
      name: 'finish_push',
      nameBg: 'Финиш пуш страна',
      nameEn: 'Push Side Finish',
      type: 'SELECT',
      productTypeId: 'pt_doors',
      isRequired: true,
      displayOrder: 3,
      icon: '🎨',
    },
    {
      id: 'at_doors_finish_pull',
      name: 'finish_pull',
      nameBg: 'Финиш пул страна',
      nameEn: 'Pull Side Finish',
      type: 'SELECT',
      productTypeId: 'pt_doors',
      isRequired: true,
      displayOrder: 4,
      icon: '🎨',
    },
    {
      id: 'at_doors_lock_type',
      name: 'lock_type',
      nameBg: 'Вид брава',
      nameEn: 'Lock Type',
      type: 'SELECT',
      productTypeId: 'pt_doors',
      isRequired: true,
      displayOrder: 5,
      icon: '🔒',
    },
    {
      id: 'at_doors_opening',
      name: 'opening_direction',
      nameBg: 'Посока отваряне',
      nameEn: 'Opening Direction',
      type: 'SELECT',
      productTypeId: 'pt_doors',
      isRequired: true,
      displayOrder: 6,
      icon: '🔄',
    },
    {
      id: 'at_doors_height',
      name: 'door_height',
      nameBg: 'Височина',
      nameEn: 'Height',
      type: 'SELECT',
      productTypeId: 'pt_doors',
      isRequired: true,
      displayOrder: 7,
      icon: '↕️',
    },
    {
      id: 'at_doors_width',
      name: 'door_width',
      nameBg: 'Ширина',
      nameEn: 'Width',
      type: 'SELECT',
      productTypeId: 'pt_doors',
      isRequired: true,
      displayOrder: 8,
      icon: '↔️',
    },
    {
      id: 'at_doors_collection',
      name: 'door_collection',
      nameBg: 'Колекция',
      nameEn: 'Collection',
      type: 'SELECT',
      productTypeId: 'pt_doors',
      isRequired: false,
      displayOrder: 9,
      icon: '📚',
    },
    // Мебели атрибути
    {
      id: 'at_furniture_category',
      name: 'furniture_category',
      nameBg: 'Категория',
      nameEn: 'Category',
      type: 'SELECT',
      productTypeId: 'pt_furniture',
      isRequired: true,
      displayOrder: 1,
      icon: '🏷️',
    },
    {
      id: 'at_furniture_material',
      name: 'furniture_material',
      nameBg: 'Материал',
      nameEn: 'Material',
      type: 'SELECT',
      productTypeId: 'pt_furniture',
      isRequired: true,
      displayOrder: 2,
      icon: '🪵',
    },
    {
      id: 'at_furniture_color',
      name: 'furniture_color',
      nameBg: 'Цвят',
      nameEn: 'Color',
      type: 'COLOR',
      productTypeId: 'pt_furniture',
      isRequired: true,
      displayOrder: 3,
      icon: '🎨',
    },
    {
      id: 'at_furniture_dimensions',
      name: 'furniture_dimensions',
      nameBg: 'Размери',
      nameEn: 'Dimensions',
      type: 'TEXT',
      productTypeId: 'pt_furniture',
      isRequired: true,
      displayOrder: 4,
      icon: '📐',
    },
    // Стенни облицовки атрибути
    {
      id: 'at_wall_type',
      name: 'wall_covering_type',
      nameBg: 'Тип облицовка',
      nameEn: 'Covering Type',
      type: 'SELECT',
      productTypeId: 'pt_wall_coverings',
      isRequired: true,
      displayOrder: 1,
      icon: '🧱',
    },
    {
      id: 'at_wall_material',
      name: 'wall_material',
      nameBg: 'Материал',
      nameEn: 'Material',
      type: 'SELECT',
      productTypeId: 'pt_wall_coverings',
      isRequired: true,
      displayOrder: 2,
      icon: '🪨',
    },
    {
      id: 'at_wall_pattern',
      name: 'wall_pattern',
      nameBg: 'Шарка',
      nameEn: 'Pattern',
      type: 'SELECT',
      productTypeId: 'pt_wall_coverings',
      isRequired: false,
      displayOrder: 3,
      icon: '🔷',
    },
    // Услуги за монтаж атрибути
    {
      id: 'at_service_type',
      name: 'service_type',
      nameBg: 'Тип услуга',
      nameEn: 'Service Type',
      type: 'SELECT',
      productTypeId: 'pt_installation_services',
      isRequired: true,
      displayOrder: 1,
      icon: '🔧',
    },
    {
      id: 'at_service_complexity',
      name: 'service_complexity',
      nameBg: 'Сложност',
      nameEn: 'Complexity',
      type: 'SELECT',
      productTypeId: 'pt_installation_services',
      isRequired: true,
      displayOrder: 2,
      icon: '⚡',
    },
    // Материали за монтаж атрибути
    {
      id: 'at_material_type',
      name: 'installation_material_type',
      nameBg: 'Тип материал',
      nameEn: 'Material Type',
      type: 'SELECT',
      productTypeId: 'pt_installation_materials',
      isRequired: true,
      displayOrder: 1,
      icon: '🛠️',
    },
    {
      id: 'at_material_usage',
      name: 'material_usage',
      nameBg: 'Приложение',
      nameEn: 'Usage',
      type: 'SELECT',
      productTypeId: 'pt_installation_materials',
      isRequired: true,
      displayOrder: 2,
      icon: '📋',
    },
    {
      id: 'at_material_package',
      name: 'material_package',
      nameBg: 'Опаковка',
      nameEn: 'Package',
      type: 'SELECT',
      productTypeId: 'pt_installation_materials',
      isRequired: true,
      displayOrder: 3,
      icon: '📦',
    },
    // Декинг и сайдинг атрибути
    {
      id: 'at_decking_type',
      name: 'decking_type',
      nameBg: 'Тип',
      nameEn: 'Type',
      type: 'SELECT',
      productTypeId: 'pt_decking_siding',
      isRequired: true,
      displayOrder: 1,
      icon: '🏡',
    },
    {
      id: 'at_decking_material',
      name: 'decking_material',
      nameBg: 'Материал',
      nameEn: 'Material',
      type: 'SELECT',
      productTypeId: 'pt_decking_siding',
      isRequired: true,
      displayOrder: 2,
      icon: '🪵',
    },
    {
      id: 'at_decking_profile',
      name: 'decking_profile',
      nameBg: 'Профил',
      nameEn: 'Profile',
      type: 'SELECT',
      productTypeId: 'pt_decking_siding',
      isRequired: true,
      displayOrder: 3,
      icon: '📐',
    },
    // Аксесоари атрибути
    {
      id: 'at_accessory_type',
      name: 'accessory_type',
      nameBg: 'Тип аксесоар',
      nameEn: 'Accessory Type',
      type: 'SELECT',
      productTypeId: 'pt_accessories',
      isRequired: true,
      displayOrder: 1,
      icon: '📦',
    },
    {
      id: 'at_accessory_material',
      name: 'accessory_material',
      nameBg: 'Материал',
      nameEn: 'Material',
      type: 'SELECT',
      productTypeId: 'pt_accessories',
      isRequired: true,
      displayOrder: 2,
      icon: '🔩',
    },
    {
      id: 'at_accessory_color',
      name: 'accessory_color',
      nameBg: 'Цвят',
      nameEn: 'Color',
      type: 'COLOR',
      productTypeId: 'pt_accessories',
      isRequired: false,
      displayOrder: 3,
      icon: '🎨',
    },
  ];

  console.log('Creating AttributeTypes...');
  for (const attributeType of attributeTypes) {
    await prisma.attributeType.upsert({
      where: { 
        productTypeId_name: {
          productTypeId: attributeType.productTypeId,
          name: attributeType.name,
        }
      },
      update: attributeType,
      create: attributeType,
    });
  }

  // Phase 1A.4: Create AttributeValues
  const attributeValues = [
    // Wood Types for Parquet
    {
      id: 'av_wood_oak_all',
      nameBg: 'Дъб',
      nameEn: 'Oak',
      icon: '🌳',
      attributeTypeId: 'at_parquet_wood_type',
      sortOrder: 1,
    },
    {
      id: 'av_wood_beech_all',
      nameBg: 'Бук',
      nameEn: 'Beech',
      icon: '🌳',
      attributeTypeId: 'at_parquet_wood_type',
      sortOrder: 2,
    },
    {
      id: 'av_wood_walnut_all',
      nameBg: 'Орех',
      nameEn: 'Walnut',
      icon: '🌰',
      attributeTypeId: 'at_parquet_wood_type',
      sortOrder: 3,
    },
    {
      id: 'av_wood_ash_all',
      nameBg: 'Ясен',
      nameEn: 'Ash',
      icon: '🌳',
      attributeTypeId: 'at_parquet_wood_type',
      sortOrder: 4,
    },
    {
      id: 'av_wood_bamboo_all',
      nameBg: 'Бамбук',
      nameEn: 'Bamboo',
      icon: '🎋',
      attributeTypeId: 'at_parquet_wood_type',
      sortOrder: 5,
    },
    {
      id: 'av_wood_cherry_all',
      nameBg: 'Череша',
      nameEn: 'Cherry',
      icon: '🍒',
      attributeTypeId: 'at_parquet_wood_type',
      sortOrder: 6,
    },
    {
      id: 'av_wood_maple_all',
      nameBg: 'Клен',
      nameEn: 'Maple',
      icon: '🍁',
      attributeTypeId: 'at_parquet_wood_type',
      sortOrder: 7,
    },
    {
      id: 'av_wood_teak_all',
      nameBg: 'Тиково дърво',
      nameEn: 'Teak',
      icon: '🌴',
      attributeTypeId: 'at_parquet_wood_type',
      sortOrder: 8,
    },
    // Construction Types for Parquet
    {
      id: 'av_const_solid_all',
      nameBg: 'Масивен',
      nameEn: 'Solid',
      icon: '🪵',
      attributeTypeId: 'at_parquet_construction',
      sortOrder: 1,
    },
    {
      id: 'av_const_engineered_all',
      nameBg: 'Инженерен',
      nameEn: 'Engineered',
      icon: '🔧',
      attributeTypeId: 'at_parquet_construction',
      sortOrder: 2,
    },
    {
      id: 'av_const_laminate_all',
      nameBg: 'Ламинат',
      nameEn: 'Laminate',
      icon: '📐',
      attributeTypeId: 'at_parquet_construction',
      sortOrder: 3,
    },
    {
      id: 'av_const_vinyl_all',
      nameBg: 'Винил',
      nameEn: 'Vinyl',
      icon: '🎯',
      attributeTypeId: 'at_parquet_construction',
      sortOrder: 4,
    },
    // Thickness for Parquet
    {
      id: 'av_thick_8mm',
      nameBg: '8мм',
      nameEn: '8mm',
      attributeTypeId: 'at_parquet_thickness',
      sortOrder: 1,
    },
    {
      id: 'av_thick_10mm',
      nameBg: '10мм',
      nameEn: '10mm',
      attributeTypeId: 'at_parquet_thickness',
      sortOrder: 2,
    },
    {
      id: 'av_thick_12mm',
      nameBg: '12мм',
      nameEn: '12mm',
      attributeTypeId: 'at_parquet_thickness',
      sortOrder: 3,
    },
    {
      id: 'av_thick_14mm',
      nameBg: '14мм',
      nameEn: '14mm',
      attributeTypeId: 'at_parquet_thickness',
      sortOrder: 4,
    },
    {
      id: 'av_thick_15mm',
      nameBg: '15мм',
      nameEn: '15mm',
      attributeTypeId: 'at_parquet_thickness',
      sortOrder: 5,
    },
    {
      id: 'av_thick_20mm',
      nameBg: '20мм',
      nameEn: '20mm',
      attributeTypeId: 'at_parquet_thickness',
      sortOrder: 6,
    },
    {
      id: 'av_thick_22mm',
      nameBg: '22мм',
      nameEn: '22mm',
      attributeTypeId: 'at_parquet_thickness',
      sortOrder: 7,
    },
    // Width for Parquet
    {
      id: 'av_width_70mm',
      nameBg: '70мм',
      nameEn: '70mm',
      attributeTypeId: 'at_parquet_width',
      sortOrder: 1,
    },
    {
      id: 'av_width_90mm',
      nameBg: '90мм',
      nameEn: '90mm',
      attributeTypeId: 'at_parquet_width',
      sortOrder: 2,
    },
    {
      id: 'av_width_120mm',
      nameBg: '120мм',
      nameEn: '120mm',
      attributeTypeId: 'at_parquet_width',
      sortOrder: 3,
    },
    {
      id: 'av_width_140mm',
      nameBg: '140мм',
      nameEn: '140mm',
      attributeTypeId: 'at_parquet_width',
      sortOrder: 4,
    },
    {
      id: 'av_width_160mm',
      nameBg: '160мм',
      nameEn: '160mm',
      attributeTypeId: 'at_parquet_width',
      sortOrder: 5,
    },
    {
      id: 'av_width_180mm',
      nameBg: '180мм',
      nameEn: '180mm',
      attributeTypeId: 'at_parquet_width',
      sortOrder: 6,
    },
    {
      id: 'av_width_200mm',
      nameBg: '200мм',
      nameEn: '200mm',
      attributeTypeId: 'at_parquet_width',
      sortOrder: 7,
    },
    {
      id: 'av_width_220mm',
      nameBg: '220мм',
      nameEn: '220mm',
      attributeTypeId: 'at_parquet_width',
      sortOrder: 8,
    },
    // Length for Parquet
    {
      id: 'av_length_400mm',
      nameBg: '400мм',
      nameEn: '400mm',
      attributeTypeId: 'at_parquet_length',
      sortOrder: 1,
    },
    {
      id: 'av_length_600mm',
      nameBg: '600мм',
      nameEn: '600mm',
      attributeTypeId: 'at_parquet_length',
      sortOrder: 2,
    },
    {
      id: 'av_length_900mm',
      nameBg: '900мм',
      nameEn: '900mm',
      attributeTypeId: 'at_parquet_length',
      sortOrder: 3,
    },
    {
      id: 'av_length_1200mm',
      nameBg: '1200мм',
      nameEn: '1200mm',
      attributeTypeId: 'at_parquet_length',
      sortOrder: 4,
    },
    {
      id: 'av_length_1500mm',
      nameBg: '1500мм',
      nameEn: '1500mm',
      attributeTypeId: 'at_parquet_length',
      sortOrder: 5,
    },
    {
      id: 'av_length_1800mm',
      nameBg: '1800мм',
      nameEn: '1800mm',
      attributeTypeId: 'at_parquet_length',
      sortOrder: 6,
    },
    {
      id: 'av_length_2000mm',
      nameBg: '2000мм',
      nameEn: '2000mm',
      attributeTypeId: 'at_parquet_length',
      sortOrder: 7,
    },
    {
      id: 'av_length_2200mm',
      nameBg: '2200мм',
      nameEn: '2200mm',
      attributeTypeId: 'at_parquet_length',
      sortOrder: 8,
    },
    {
      id: 'av_length_variable',
      nameBg: 'Променлива',
      nameEn: 'Variable',
      icon: '🔀',
      attributeTypeId: 'at_parquet_length',
      sortOrder: 9,
    },
    // Colors for Parquet
    {
      id: 'av_color_natural',
      nameBg: 'Натурален',
      nameEn: 'Natural',
      colorCode: '#D2B48C',
      attributeTypeId: 'at_parquet_color',
      sortOrder: 1,
    },
    {
      id: 'av_color_dark_oak',
      nameBg: 'Тъмен дъб',
      nameEn: 'Dark Oak',
      colorCode: '#8B4513',
      attributeTypeId: 'at_parquet_color',
      sortOrder: 2,
    },
    {
      id: 'av_color_walnut',
      nameBg: 'Орех',
      nameEn: 'Walnut',
      colorCode: '#654321',
      attributeTypeId: 'at_parquet_color',
      sortOrder: 3,
    },
    {
      id: 'av_color_white',
      nameBg: 'Бял',
      nameEn: 'White',
      colorCode: '#F5F5DC',
      attributeTypeId: 'at_parquet_color',
      sortOrder: 4,
    },
    {
      id: 'av_color_grey',
      nameBg: 'Сив',
      nameEn: 'Grey',
      colorCode: '#808080',
      attributeTypeId: 'at_parquet_color',
      sortOrder: 5,
    },
    {
      id: 'av_color_black',
      nameBg: 'Черен',
      nameEn: 'Black',
      colorCode: '#2C2C2C',
      attributeTypeId: 'at_parquet_color',
      sortOrder: 6,
    },
    {
      id: 'av_color_honey',
      nameBg: 'Меден',
      nameEn: 'Honey',
      colorCode: '#FFB347',
      attributeTypeId: 'at_parquet_color',
      sortOrder: 7,
    },
    {
      id: 'av_color_cognac',
      nameBg: 'Коняк',
      nameEn: 'Cognac',
      colorCode: '#9F4E3B',
      attributeTypeId: 'at_parquet_color',
      sortOrder: 8,
    },
    {
      id: 'av_color_chocolate',
      nameBg: 'Шоколад',
      nameEn: 'Chocolate',
      colorCode: '#3B2414',
      attributeTypeId: 'at_parquet_color',
      sortOrder: 9,
    },
    // Finish for Parquet
    {
      id: 'av_finish_matt',
      nameBg: 'Мат',
      nameEn: 'Matt',
      icon: '🔵',
      attributeTypeId: 'at_parquet_finish',
      sortOrder: 1,
    },
    {
      id: 'av_finish_satin',
      nameBg: 'Сатен',
      nameEn: 'Satin',
      icon: '✨',
      attributeTypeId: 'at_parquet_finish',
      sortOrder: 2,
    },
    {
      id: 'av_finish_gloss',
      nameBg: 'Гланц',
      nameEn: 'Gloss',
      icon: '💎',
      attributeTypeId: 'at_parquet_finish',
      sortOrder: 3,
    },
    {
      id: 'av_finish_oil',
      nameBg: 'Масло',
      nameEn: 'Oil',
      icon: '💧',
      attributeTypeId: 'at_parquet_finish',
      sortOrder: 4,
    },
    {
      id: 'av_finish_lacquer',
      nameBg: 'Лак',
      nameEn: 'Lacquer',
      icon: '🛡️',
      attributeTypeId: 'at_parquet_finish',
      sortOrder: 5,
    },
    {
      id: 'av_finish_brushed',
      nameBg: 'Четкан',
      nameEn: 'Brushed',
      icon: '🖌️',
      attributeTypeId: 'at_parquet_finish',
      sortOrder: 6,
    },
    {
      id: 'av_finish_raw',
      nameBg: 'Суров',
      nameEn: 'Raw',
      icon: '🌲',
      attributeTypeId: 'at_parquet_finish',
      sortOrder: 7,
    },
    // Selection for Parquet
    {
      id: 'av_select_prime',
      nameBg: 'Прайм',
      nameEn: 'Prime',
      icon: '⭐',
      attributeTypeId: 'at_parquet_selection',
      sortOrder: 1,
    },
    {
      id: 'av_select_select',
      nameBg: 'Селект',
      nameEn: 'Select',
      icon: '🌟',
      attributeTypeId: 'at_parquet_selection',
      sortOrder: 2,
    },
    {
      id: 'av_select_nature',
      nameBg: 'Натюр',
      nameEn: 'Nature',
      icon: '🍃',
      attributeTypeId: 'at_parquet_selection',
      sortOrder: 3,
    },
    {
      id: 'av_select_rustic',
      nameBg: 'Рустик',
      nameEn: 'Rustic',
      icon: '🏚️',
      attributeTypeId: 'at_parquet_selection',
      sortOrder: 4,
    },
    {
      id: 'av_select_country',
      nameBg: 'Кънтри',
      nameEn: 'Country',
      icon: '🌾',
      attributeTypeId: 'at_parquet_selection',
      sortOrder: 5,
    },
    // Door Types
    {
      id: 'av_door_interior',
      nameBg: 'Интериорна',
      nameEn: 'Interior',
      icon: '🚪',
      attributeTypeId: 'at_doors_type',
      sortOrder: 1,
    },
    {
      id: 'av_door_entrance',
      nameBg: 'Входна',
      nameEn: 'Entrance',
      icon: '🏠',
      attributeTypeId: 'at_doors_type',
      sortOrder: 2,
    },
    {
      id: 'av_door_sliding',
      nameBg: 'Плъзгаща',
      nameEn: 'Sliding',
      icon: '↔️',
      attributeTypeId: 'at_doors_type',
      sortOrder: 3,
    },
    {
      id: 'av_door_folding',
      nameBg: 'Сгъваема',
      nameEn: 'Folding',
      icon: '📐',
      attributeTypeId: 'at_doors_type',
      sortOrder: 4,
    },
    {
      id: 'av_door_pivot',
      nameBg: 'Пивот',
      nameEn: 'Pivot',
      icon: '🔄',
      attributeTypeId: 'at_doors_type',
      sortOrder: 5,
    },
    // Frame Materials for Doors
    {
      id: 'av_frame_wood',
      nameBg: 'Дърво',
      nameEn: 'Wood',
      icon: '🪵',
      attributeTypeId: 'at_doors_frame_material',
      sortOrder: 1,
    },
    {
      id: 'av_frame_mdf',
      nameBg: 'MDF',
      nameEn: 'MDF',
      icon: '📦',
      attributeTypeId: 'at_doors_frame_material',
      sortOrder: 2,
    },
    {
      id: 'av_frame_metal',
      nameBg: 'Метал',
      nameEn: 'Metal',
      icon: '🔩',
      attributeTypeId: 'at_doors_frame_material',
      sortOrder: 3,
    },
    {
      id: 'av_frame_aluminum',
      nameBg: 'Алуминий',
      nameEn: 'Aluminum',
      icon: '🪙',
      attributeTypeId: 'at_doors_frame_material',
      sortOrder: 4,
    },
    // Door Finishes
    {
      id: 'av_door_finish_laminate',
      nameBg: 'Ламинат',
      nameEn: 'Laminate',
      attributeTypeId: 'at_doors_finish_push',
      sortOrder: 1,
    },
    {
      id: 'av_door_finish_veneer',
      nameBg: 'Фурнир',
      nameEn: 'Veneer',
      attributeTypeId: 'at_doors_finish_push',
      sortOrder: 2,
    },
    {
      id: 'av_door_finish_painted',
      nameBg: 'Боядисан',
      nameEn: 'Painted',
      attributeTypeId: 'at_doors_finish_push',
      sortOrder: 3,
    },
    {
      id: 'av_door_finish_glass',
      nameBg: 'Стъкло',
      nameEn: 'Glass',
      icon: '🪟',
      attributeTypeId: 'at_doors_finish_push',
      sortOrder: 4,
    },
    // Also for pull side
    {
      id: 'av_door_finish_pull_laminate',
      nameBg: 'Ламинат',
      nameEn: 'Laminate',
      attributeTypeId: 'at_doors_finish_pull',
      sortOrder: 1,
    },
    {
      id: 'av_door_finish_pull_veneer',
      nameBg: 'Фурнир',
      nameEn: 'Veneer',
      attributeTypeId: 'at_doors_finish_pull',
      sortOrder: 2,
    },
    {
      id: 'av_door_finish_pull_painted',
      nameBg: 'Боядисан',
      nameEn: 'Painted',
      attributeTypeId: 'at_doors_finish_pull',
      sortOrder: 3,
    },
    {
      id: 'av_door_finish_pull_glass',
      nameBg: 'Стъкло',
      nameEn: 'Glass',
      icon: '🪟',
      attributeTypeId: 'at_doors_finish_pull',
      sortOrder: 4,
    },
    // Lock Types for Doors
    {
      id: 'av_lock_standard',
      nameBg: 'Стандартна',
      nameEn: 'Standard',
      icon: '🔒',
      attributeTypeId: 'at_doors_lock_type',
      sortOrder: 1,
    },
    {
      id: 'av_lock_bathroom',
      nameBg: 'За баня',
      nameEn: 'Bathroom',
      icon: '🚿',
      attributeTypeId: 'at_doors_lock_type',
      sortOrder: 2,
    },
    {
      id: 'av_lock_cylinder',
      nameBg: 'Секретна',
      nameEn: 'Cylinder',
      icon: '🔐',
      attributeTypeId: 'at_doors_lock_type',
      sortOrder: 3,
    },
    {
      id: 'av_lock_magnetic',
      nameBg: 'Магнитна',
      nameEn: 'Magnetic',
      icon: '🧲',
      attributeTypeId: 'at_doors_lock_type',
      sortOrder: 4,
    },
    {
      id: 'av_lock_none',
      nameBg: 'Без брава',
      nameEn: 'No Lock',
      icon: '🚫',
      attributeTypeId: 'at_doors_lock_type',
      sortOrder: 5,
    },
    // Opening Direction for Doors
    {
      id: 'av_opening_left',
      nameBg: 'Лява',
      nameEn: 'Left',
      icon: '⬅️',
      attributeTypeId: 'at_doors_opening',
      sortOrder: 1,
    },
    {
      id: 'av_opening_right',
      nameBg: 'Дясна',
      nameEn: 'Right',
      icon: '➡️',
      attributeTypeId: 'at_doors_opening',
      sortOrder: 2,
    },
    {
      id: 'av_opening_double',
      nameBg: 'Двукрила',
      nameEn: 'Double',
      icon: '↔️',
      attributeTypeId: 'at_doors_opening',
      sortOrder: 3,
    },
    // Door Heights
    {
      id: 'av_door_height_2000',
      nameBg: '2000мм',
      nameEn: '2000mm',
      attributeTypeId: 'at_doors_height',
      sortOrder: 1,
    },
    {
      id: 'av_door_height_2100',
      nameBg: '2100мм',
      nameEn: '2100mm',
      attributeTypeId: 'at_doors_height',
      sortOrder: 2,
    },
    {
      id: 'av_door_height_2200',
      nameBg: '2200мм',
      nameEn: '2200mm',
      attributeTypeId: 'at_doors_height',
      sortOrder: 3,
    },
    {
      id: 'av_door_height_2400',
      nameBg: '2400мм',
      nameEn: '2400mm',
      attributeTypeId: 'at_doors_height',
      sortOrder: 4,
    },
    // Door Widths
    {
      id: 'av_door_width_600',
      nameBg: '600мм',
      nameEn: '600mm',
      attributeTypeId: 'at_doors_width',
      sortOrder: 1,
    },
    {
      id: 'av_door_width_700',
      nameBg: '700мм',
      nameEn: '700mm',
      attributeTypeId: 'at_doors_width',
      sortOrder: 2,
    },
    {
      id: 'av_door_width_800',
      nameBg: '800мм',
      nameEn: '800mm',
      attributeTypeId: 'at_doors_width',
      sortOrder: 3,
    },
    {
      id: 'av_door_width_900',
      nameBg: '900мм',
      nameEn: '900mm',
      attributeTypeId: 'at_doors_width',
      sortOrder: 4,
    },
    {
      id: 'av_door_width_1000',
      nameBg: '1000мм',
      nameEn: '1000mm',
      attributeTypeId: 'at_doors_width',
      sortOrder: 5,
    },
    // Furniture Categories
    {
      id: 'av_furn_cat_tables',
      nameBg: 'Маси',
      nameEn: 'Tables',
      icon: '🪑',
      attributeTypeId: 'at_furniture_category',
      sortOrder: 1,
    },
    {
      id: 'av_furn_cat_chairs',
      nameBg: 'Столове',
      nameEn: 'Chairs',
      icon: '💺',
      attributeTypeId: 'at_furniture_category',
      sortOrder: 2,
    },
    {
      id: 'av_furn_cat_cabinets',
      nameBg: 'Шкафове',
      nameEn: 'Cabinets',
      icon: '🗄️',
      attributeTypeId: 'at_furniture_category',
      sortOrder: 3,
    },
    {
      id: 'av_furn_cat_sofas',
      nameBg: 'Дивани',
      nameEn: 'Sofas',
      icon: '🛋️',
      attributeTypeId: 'at_furniture_category',
      sortOrder: 4,
    },
    {
      id: 'av_furn_cat_beds',
      nameBg: 'Легла',
      nameEn: 'Beds',
      icon: '🛏️',
      attributeTypeId: 'at_furniture_category',
      sortOrder: 5,
    },
    {
      id: 'av_furn_cat_outdoor',
      nameBg: 'Градински',
      nameEn: 'Outdoor',
      icon: '🪴',
      attributeTypeId: 'at_furniture_category',
      sortOrder: 6,
    },
    // Furniture Materials
    {
      id: 'av_furn_mat_solid_wood',
      nameBg: 'Масивно дърво',
      nameEn: 'Solid Wood',
      icon: '🪵',
      attributeTypeId: 'at_furniture_material',
      sortOrder: 1,
    },
    {
      id: 'av_furn_mat_mdf',
      nameBg: 'MDF',
      nameEn: 'MDF',
      attributeTypeId: 'at_furniture_material',
      sortOrder: 2,
    },
    {
      id: 'av_furn_mat_metal',
      nameBg: 'Метал',
      nameEn: 'Metal',
      icon: '🔩',
      attributeTypeId: 'at_furniture_material',
      sortOrder: 3,
    },
    {
      id: 'av_furn_mat_glass',
      nameBg: 'Стъкло',
      nameEn: 'Glass',
      icon: '🪟',
      attributeTypeId: 'at_furniture_material',
      sortOrder: 4,
    },
    {
      id: 'av_furn_mat_leather',
      nameBg: 'Кожа',
      nameEn: 'Leather',
      icon: '🐄',
      attributeTypeId: 'at_furniture_material',
      sortOrder: 5,
    },
    {
      id: 'av_furn_mat_fabric',
      nameBg: 'Текстил',
      nameEn: 'Fabric',
      icon: '🧵',
      attributeTypeId: 'at_furniture_material',
      sortOrder: 6,
    },
    // Furniture Colors
    {
      id: 'av_furn_color_white',
      nameBg: 'Бял',
      nameEn: 'White',
      colorCode: '#FFFFFF',
      attributeTypeId: 'at_furniture_color',
      sortOrder: 1,
    },
    {
      id: 'av_furn_color_black',
      nameBg: 'Черен',
      nameEn: 'Black',
      colorCode: '#000000',
      attributeTypeId: 'at_furniture_color',
      sortOrder: 2,
    },
    {
      id: 'av_furn_color_grey',
      nameBg: 'Сив',
      nameEn: 'Grey',
      colorCode: '#808080',
      attributeTypeId: 'at_furniture_color',
      sortOrder: 3,
    },
    {
      id: 'av_furn_color_brown',
      nameBg: 'Кафяв',
      nameEn: 'Brown',
      colorCode: '#8B4513',
      attributeTypeId: 'at_furniture_color',
      sortOrder: 4,
    },
    {
      id: 'av_furn_color_beige',
      nameBg: 'Бежов',
      nameEn: 'Beige',
      colorCode: '#F5F5DC',
      attributeTypeId: 'at_furniture_color',
      sortOrder: 5,
    },
    // Wall Covering Types
    {
      id: 'av_wall_type_panel',
      nameBg: 'Панел',
      nameEn: 'Panel',
      icon: '🧱',
      attributeTypeId: 'at_wall_type',
      sortOrder: 1,
    },
    {
      id: 'av_wall_type_3d',
      nameBg: '3D облицовка',
      nameEn: '3D Covering',
      icon: '🔷',
      attributeTypeId: 'at_wall_type',
      sortOrder: 2,
    },
    {
      id: 'av_wall_type_acoustic',
      nameBg: 'Акустичен',
      nameEn: 'Acoustic',
      icon: '🔇',
      attributeTypeId: 'at_wall_type',
      sortOrder: 3,
    },
    {
      id: 'av_wall_type_decorative',
      nameBg: 'Декоративен',
      nameEn: 'Decorative',
      icon: '🎨',
      attributeTypeId: 'at_wall_type',
      sortOrder: 4,
    },
    // Wall Materials
    {
      id: 'av_wall_mat_wood',
      nameBg: 'Дърво',
      nameEn: 'Wood',
      icon: '🪵',
      attributeTypeId: 'at_wall_material',
      sortOrder: 1,
    },
    {
      id: 'av_wall_mat_cork',
      nameBg: 'Корк',
      nameEn: 'Cork',
      icon: '🟫',
      attributeTypeId: 'at_wall_material',
      sortOrder: 2,
    },
    {
      id: 'av_wall_mat_fabric',
      nameBg: 'Текстил',
      nameEn: 'Fabric',
      icon: '🧵',
      attributeTypeId: 'at_wall_material',
      sortOrder: 3,
    },
    {
      id: 'av_wall_mat_metal',
      nameBg: 'Метал',
      nameEn: 'Metal',
      icon: '🔩',
      attributeTypeId: 'at_wall_material',
      sortOrder: 4,
    },
    // Service Types
    {
      id: 'av_service_parquet_install',
      nameBg: 'Монтаж паркет',
      nameEn: 'Parquet Installation',
      icon: '🔨',
      attributeTypeId: 'at_service_type',
      sortOrder: 1,
    },
    {
      id: 'av_service_door_install',
      nameBg: 'Монтаж врати',
      nameEn: 'Door Installation',
      icon: '🚪',
      attributeTypeId: 'at_service_type',
      sortOrder: 2,
    },
    {
      id: 'av_service_sanding',
      nameBg: 'Циклене',
      nameEn: 'Sanding',
      icon: '🪵',
      attributeTypeId: 'at_service_type',
      sortOrder: 3,
    },
    {
      id: 'av_service_repair',
      nameBg: 'Ремонт',
      nameEn: 'Repair',
      icon: '🔧',
      attributeTypeId: 'at_service_type',
      sortOrder: 4,
    },
    {
      id: 'av_service_measurement',
      nameBg: 'Замерване',
      nameEn: 'Measurement',
      icon: '📏',
      attributeTypeId: 'at_service_type',
      sortOrder: 5,
    },
    // Service Complexity
    {
      id: 'av_complexity_simple',
      nameBg: 'Лесен',
      nameEn: 'Simple',
      icon: '🟢',
      attributeTypeId: 'at_service_complexity',
      sortOrder: 1,
    },
    {
      id: 'av_complexity_medium',
      nameBg: 'Среден',
      nameEn: 'Medium',
      icon: '🟡',
      attributeTypeId: 'at_service_complexity',
      sortOrder: 2,
    },
    {
      id: 'av_complexity_complex',
      nameBg: 'Сложен',
      nameEn: 'Complex',
      icon: '🔴',
      attributeTypeId: 'at_service_complexity',
      sortOrder: 3,
    },
    // Installation Material Types
    {
      id: 'av_inst_mat_adhesive',
      nameBg: 'Лепило',
      nameEn: 'Adhesive',
      icon: '🧴',
      attributeTypeId: 'at_material_type',
      sortOrder: 1,
    },
    {
      id: 'av_inst_mat_underlay',
      nameBg: 'Подложка',
      nameEn: 'Underlay',
      icon: '📄',
      attributeTypeId: 'at_material_type',
      sortOrder: 2,
    },
    {
      id: 'av_inst_mat_primer',
      nameBg: 'Грунд',
      nameEn: 'Primer',
      icon: '🪣',
      attributeTypeId: 'at_material_type',
      sortOrder: 3,
    },
    {
      id: 'av_inst_mat_screws',
      nameBg: 'Крепежи',
      nameEn: 'Fasteners',
      icon: '🔩',
      attributeTypeId: 'at_material_type',
      sortOrder: 4,
    },
    {
      id: 'av_inst_mat_sealant',
      nameBg: 'Уплътнител',
      nameEn: 'Sealant',
      icon: '🧊',
      attributeTypeId: 'at_material_type',
      sortOrder: 5,
    },
    // Material Usage
    {
      id: 'av_usage_parquet',
      nameBg: 'За паркет',
      nameEn: 'For Parquet',
      attributeTypeId: 'at_material_usage',
      sortOrder: 1,
    },
    {
      id: 'av_usage_doors',
      nameBg: 'За врати',
      nameEn: 'For Doors',
      attributeTypeId: 'at_material_usage',
      sortOrder: 2,
    },
    {
      id: 'av_usage_universal',
      nameBg: 'Универсално',
      nameEn: 'Universal',
      attributeTypeId: 'at_material_usage',
      sortOrder: 3,
    },
    // Material Package
    {
      id: 'av_package_bucket',
      nameBg: 'Кофа',
      nameEn: 'Bucket',
      icon: '🪣',
      attributeTypeId: 'at_material_package',
      sortOrder: 1,
    },
    {
      id: 'av_package_tube',
      nameBg: 'Туба',
      nameEn: 'Tube',
      icon: '🧴',
      attributeTypeId: 'at_material_package',
      sortOrder: 2,
    },
    {
      id: 'av_package_roll',
      nameBg: 'Ролка',
      nameEn: 'Roll',
      icon: '🧻',
      attributeTypeId: 'at_material_package',
      sortOrder: 3,
    },
    {
      id: 'av_package_bag',
      nameBg: 'Чувал',
      nameEn: 'Bag',
      icon: '💰',
      attributeTypeId: 'at_material_package',
      sortOrder: 4,
    },
    {
      id: 'av_package_box',
      nameBg: 'Кутия',
      nameEn: 'Box',
      icon: '📦',
      attributeTypeId: 'at_material_package',
      sortOrder: 5,
    },
    // Decking Types
    {
      id: 'av_deck_type_composite',
      nameBg: 'Композитен',
      nameEn: 'Composite',
      icon: '🔲',
      attributeTypeId: 'at_decking_type',
      sortOrder: 1,
    },
    {
      id: 'av_deck_type_wood',
      nameBg: 'Дървен',
      nameEn: 'Wood',
      icon: '🪵',
      attributeTypeId: 'at_decking_type',
      sortOrder: 2,
    },
    {
      id: 'av_deck_type_wpc',
      nameBg: 'WPC',
      nameEn: 'WPC',
      icon: '🟫',
      attributeTypeId: 'at_decking_type',
      sortOrder: 3,
    },
    {
      id: 'av_deck_type_siding',
      nameBg: 'Сайдинг',
      nameEn: 'Siding',
      icon: '🏠',
      attributeTypeId: 'at_decking_type',
      sortOrder: 4,
    },
    // Decking Materials
    {
      id: 'av_deck_mat_hardwood',
      nameBg: 'Твърда дървесина',
      nameEn: 'Hardwood',
      icon: '🌳',
      attributeTypeId: 'at_decking_material',
      sortOrder: 1,
    },
    {
      id: 'av_deck_mat_softwood',
      nameBg: 'Мека дървесина',
      nameEn: 'Softwood',
      icon: '🌲',
      attributeTypeId: 'at_decking_material',
      sortOrder: 2,
    },
    {
      id: 'av_deck_mat_composite',
      nameBg: 'Композит',
      nameEn: 'Composite',
      icon: '🔲',
      attributeTypeId: 'at_decking_material',
      sortOrder: 3,
    },
    {
      id: 'av_deck_mat_bamboo',
      nameBg: 'Бамбук',
      nameEn: 'Bamboo',
      icon: '🎋',
      attributeTypeId: 'at_decking_material',
      sortOrder: 4,
    },
    // Decking Profiles
    {
      id: 'av_deck_profile_smooth',
      nameBg: 'Гладък',
      nameEn: 'Smooth',
      attributeTypeId: 'at_decking_profile',
      sortOrder: 1,
    },
    {
      id: 'av_deck_profile_grooved',
      nameBg: 'Жлебован',
      nameEn: 'Grooved',
      attributeTypeId: 'at_decking_profile',
      sortOrder: 2,
    },
    {
      id: 'av_deck_profile_ribbed',
      nameBg: 'Ребрест',
      nameEn: 'Ribbed',
      attributeTypeId: 'at_decking_profile',
      sortOrder: 3,
    },
    // Accessory Types
    {
      id: 'av_acc_type_skirting',
      nameBg: 'Первази',
      nameEn: 'Skirting',
      icon: '📏',
      attributeTypeId: 'at_accessory_type',
      sortOrder: 1,
    },
    {
      id: 'av_acc_type_profile',
      nameBg: 'Профили',
      nameEn: 'Profiles',
      icon: '📐',
      attributeTypeId: 'at_accessory_type',
      sortOrder: 2,
    },
    {
      id: 'av_acc_type_transition',
      nameBg: 'Преходни лайсни',
      nameEn: 'Transition Strips',
      icon: '🔗',
      attributeTypeId: 'at_accessory_type',
      sortOrder: 3,
    },
    {
      id: 'av_acc_type_corner',
      nameBg: 'Ъглови елементи',
      nameEn: 'Corner Elements',
      icon: '📐',
      attributeTypeId: 'at_accessory_type',
      sortOrder: 4,
    },
    // Accessory Materials
    {
      id: 'av_acc_mat_wood',
      nameBg: 'Дърво',
      nameEn: 'Wood',
      icon: '🪵',
      attributeTypeId: 'at_accessory_material',
      sortOrder: 1,
    },
    {
      id: 'av_acc_mat_mdf',
      nameBg: 'MDF',
      nameEn: 'MDF',
      attributeTypeId: 'at_accessory_material',
      sortOrder: 2,
    },
    {
      id: 'av_acc_mat_aluminum',
      nameBg: 'Алуминий',
      nameEn: 'Aluminum',
      icon: '🪙',
      attributeTypeId: 'at_accessory_material',
      sortOrder: 3,
    },
    {
      id: 'av_acc_mat_plastic',
      nameBg: 'Пластмаса',
      nameEn: 'Plastic',
      icon: '🔲',
      attributeTypeId: 'at_accessory_material',
      sortOrder: 4,
    },
    // Accessory Colors
    {
      id: 'av_acc_color_white',
      nameBg: 'Бял',
      nameEn: 'White',
      colorCode: '#FFFFFF',
      attributeTypeId: 'at_accessory_color',
      sortOrder: 1,
    },
    {
      id: 'av_acc_color_oak',
      nameBg: 'Дъб',
      nameEn: 'Oak',
      colorCode: '#D2B48C',
      attributeTypeId: 'at_accessory_color',
      sortOrder: 2,
    },
    {
      id: 'av_acc_color_walnut',
      nameBg: 'Орех',
      nameEn: 'Walnut',
      colorCode: '#654321',
      attributeTypeId: 'at_accessory_color',
      sortOrder: 3,
    },
    {
      id: 'av_acc_color_grey',
      nameBg: 'Сив',
      nameEn: 'Grey',
      colorCode: '#808080',
      attributeTypeId: 'at_accessory_color',
      sortOrder: 4,
    },
    {
      id: 'av_acc_color_black',
      nameBg: 'Черен',
      nameEn: 'Black',
      colorCode: '#000000',
      attributeTypeId: 'at_accessory_color',
      sortOrder: 5,
    },
  ];

  console.log('Creating AttributeValues...');
  for (const attributeValue of attributeValues) {
    await prisma.attributeValue.upsert({
      where: { id: attributeValue.id },
      update: attributeValue,
      create: attributeValue,
    });
  }

  // Create manufacturer-specific attribute values
  const manufacturerSpecificValues = [
    // Foglie d'Oro specific collections
    {
      id: 'av_collection_foglie_essenze',
      nameBg: 'Essenze Nobili',
      nameEn: 'Essenze Nobili',
      icon: '👑',
      attributeTypeId: 'at_parquet_collection',
      manufacturerId: 'mf_foglie_doro',
      sortOrder: 1,
    },
    {
      id: 'av_collection_foglie_luxury',
      nameBg: 'Luxury Collection',
      nameEn: 'Luxury Collection',
      icon: '💎',
      attributeTypeId: 'at_parquet_collection',
      manufacturerId: 'mf_foglie_doro',
      sortOrder: 2,
    },
    // Salis specific collections
    {
      id: 'av_collection_salis_classic',
      nameBg: 'Classic Line',
      nameEn: 'Classic Line',
      icon: '📜',
      attributeTypeId: 'at_parquet_collection',
      manufacturerId: 'mf_salis',
      sortOrder: 1,
    },
    {
      id: 'av_collection_salis_modern',
      nameBg: 'Modern Style',
      nameEn: 'Modern Style',
      icon: '🎯',
      attributeTypeId: 'at_parquet_collection',
      manufacturerId: 'mf_salis',
      sortOrder: 2,
    },
    // Weitzer specific collections
    {
      id: 'av_collection_weitzer_authentic',
      nameBg: 'Authentic',
      nameEn: 'Authentic',
      icon: '🌿',
      attributeTypeId: 'at_parquet_collection',
      manufacturerId: 'mf_weitzer',
      sortOrder: 1,
    },
    {
      id: 'av_collection_weitzer_pro',
      nameBg: 'Weitzer Pro',
      nameEn: 'Weitzer Pro',
      icon: '🏆',
      attributeTypeId: 'at_parquet_collection',
      manufacturerId: 'mf_weitzer',
      sortOrder: 2,
    },
    // Bluinterni door collections
    {
      id: 'av_collection_blu_minimal',
      nameBg: 'Minimal',
      nameEn: 'Minimal',
      icon: '⚪',
      attributeTypeId: 'at_doors_collection',
      manufacturerId: 'mf_bluinterni',
      sortOrder: 1,
    },
    {
      id: 'av_collection_blu_design',
      nameBg: 'Design',
      nameEn: 'Design',
      icon: '🎨',
      attributeTypeId: 'at_doors_collection',
      manufacturerId: 'mf_bluinterni',
      sortOrder: 2,
    },
    {
      id: 'av_collection_blu_classic',
      nameBg: 'Classic',
      nameEn: 'Classic',
      icon: '🏛️',
      attributeTypeId: 'at_doors_collection',
      manufacturerId: 'mf_bluinterni',
      sortOrder: 3,
    },
  ];

  console.log('Creating manufacturer-specific AttributeValues...');
  for (const value of manufacturerSpecificValues) {
    await prisma.attributeValue.upsert({
      where: { id: value.id },
      update: value,
      create: value,
    });
  }

  // Create sample products
  const products = [
    {
      code: 'FOG-OAK-001',
      nameBg: 'Дъб Класик Essenze',
      nameEn: 'Oak Classic Essenze',
      productTypeId: 'pt_parquet',
      manufacturerId: 'mf_foglie_doro',
      supplier: 'Foglie d\'Oro Italia',
      unit: 'm2',
      packageSize: '2.184',
      costEur: 65.50,
      costBgn: 128.12,
      saleBgn: 166.55,
      saleEur: 85.15,
      markup: 30,
      isActive: true,
      isRecommended: true,
      isNew: false,
    },
    {
      code: 'SAL-WAL-002',
      nameBg: 'Орех Модерн',
      nameEn: 'Walnut Modern',
      productTypeId: 'pt_parquet',
      manufacturerId: 'mf_salis',
      supplier: 'Salis Italia',
      unit: 'm2',
      packageSize: '2.016',
      costEur: 72.00,
      costBgn: 140.83,
      saleBgn: 183.08,
      saleEur: 93.60,
      markup: 30,
      isActive: true,
      isRecommended: false,
      isNew: true,
    },
    {
      code: 'BLU-MIN-001',
      nameBg: 'Минимал Бяла',
      nameEn: 'Minimal White',
      productTypeId: 'pt_doors',
      manufacturerId: 'mf_bluinterni',
      supplier: 'Bluinterni Italia',
      unit: 'бр',
      packageSize: '1',
      costEur: 320.00,
      costBgn: 625.92,
      saleBgn: 813.70,
      saleEur: 416.00,
      markup: 30,
      isActive: true,
      isRecommended: true,
      isNew: false,
    },
  ];

  console.log('Creating sample Products...');
  const createdProducts = [];
  for (const product of products) {
    const createdProduct = await prisma.product.upsert({
      where: { code: product.code },
      update: product,
      create: product,
    });
    createdProducts.push(createdProduct);
  }

  // Create product attribute values for the sample products
  const foglieDOroProduct = createdProducts.find(p => p.code === 'FOG-OAK-001');
  const salıswalnutProduct = createdProducts.find(p => p.code === 'SAL-WAL-002');
  const bluinterniProduct = createdProducts.find(p => p.code === 'BLU-MIN-001');

  if (!foglieDOroProduct || !salıswalnutProduct || !bluinterniProduct) {
    throw new Error('Failed to create sample products');
  }

  const productAttributeValues = [
    // Foglie Oak Classic attributes
    {
      productId: foglieDOroProduct.id,
      attributeTypeId: 'at_parquet_wood_type',
      attributeValueId: 'av_wood_oak_all',
    },
    {
      productId: foglieDOroProduct.id,
      attributeTypeId: 'at_parquet_construction',
      attributeValueId: 'av_const_engineered_all',
    },
    {
      productId: foglieDOroProduct.id,
      attributeTypeId: 'at_parquet_thickness',
      attributeValueId: 'av_thick_14mm',
    },
    {
      productId: foglieDOroProduct.id,
      attributeTypeId: 'at_parquet_width',
      attributeValueId: 'av_width_140mm',
    },
    {
      productId: foglieDOroProduct.id,
      attributeTypeId: 'at_parquet_length',
      attributeValueId: 'av_length_variable',
    },
    {
      productId: foglieDOroProduct.id,
      attributeTypeId: 'at_parquet_color',
      attributeValueId: 'av_color_natural',
    },
    {
      productId: foglieDOroProduct.id,
      attributeTypeId: 'at_parquet_finish',
      attributeValueId: 'av_finish_oil',
    },
    {
      productId: foglieDOroProduct.id,
      attributeTypeId: 'at_parquet_selection',
      attributeValueId: 'av_select_select',
    },
    {
      productId: foglieDOroProduct.id,
      attributeTypeId: 'at_parquet_collection',
      attributeValueId: 'av_collection_foglie_essenze',
    },
    // Bluinterni Minimal White door attributes
    {
      productId: bluinterniProduct.id,
      attributeTypeId: 'at_doors_type',
      attributeValueId: 'av_door_interior',
    },
    {
      productId: bluinterniProduct.id,
      attributeTypeId: 'at_doors_frame_material',
      attributeValueId: 'av_frame_wood',
    },
    {
      productId: bluinterniProduct.id,
      attributeTypeId: 'at_doors_finish_push',
      attributeValueId: 'av_door_finish_painted',
    },
    {
      productId: bluinterniProduct.id,
      attributeTypeId: 'at_doors_finish_pull',
      attributeValueId: 'av_door_finish_pull_painted',
    },
    {
      productId: bluinterniProduct.id,
      attributeTypeId: 'at_doors_lock_type',
      attributeValueId: 'av_lock_standard',
    },
    {
      productId: bluinterniProduct.id,
      attributeTypeId: 'at_doors_opening',
      attributeValueId: 'av_opening_right',
    },
    {
      productId: bluinterniProduct.id,
      attributeTypeId: 'at_doors_height',
      attributeValueId: 'av_door_height_2100',
    },
    {
      productId: bluinterniProduct.id,
      attributeTypeId: 'at_doors_width',
      attributeValueId: 'av_door_width_800',
    },
    {
      productId: bluinterniProduct.id,
      attributeTypeId: 'at_doors_collection',
      attributeValueId: 'av_collection_blu_minimal',
    },
  ];

  console.log('Creating ProductAttributeValues...');
  for (const pav of productAttributeValues) {
    await prisma.productAttributeValue.upsert({
      where: { 
        productId_attributeTypeId: {
          productId: pav.productId,
          attributeTypeId: pav.attributeTypeId,
        }
      },
      update: pav,
      create: pav,
    });
  }

  // Create sample Clients
  const clients = [
    {
      firstName: 'Иван',
      lastName: 'Петров',
      email: 'ivan.petrov@email.bg',
      phone: '+359888123456',
      address: 'ул. Витоша 15, София 1000',
      hasCompany: false,
      isActive: true,
    },
    {
      firstName: 'Мария',
      lastName: 'Георгиева',
      email: 'maria.georgieva@company.bg',
      phone: '+359887654321',
      address: 'бул. България 58, Пловдив 4000',
      hasCompany: true,
      companyName: 'Георгиева ЕООД',
      isActive: true,
    },
    {
      firstName: 'Стефан',
      lastName: 'Димитров',
      email: 'stefan@architech.bg',
      phone: '+359899111222',
      address: 'ул. Княз Борис I 123, Варна 9000',
      hasCompany: true,
      companyName: 'Architech Studio',
      isArchitect: true,
      commissionPercent: 12.0,
      isActive: true,
    },
    {
      firstName: 'Елена',
      lastName: 'Николова',
      email: 'elena.nikolova@gmail.com',
      phone: '+359878333444',
      address: 'ж.к. Младост 2, бл. 234, ап. 56, София 1799',
      hasCompany: false,
      isActive: true,
    },
    {
      firstName: 'Георги',
      lastName: 'Стоянов',
      email: 'g.stoyanov@constructions.bg',
      phone: '+359887999888',
      address: 'ул. Раковски 78, Бургас 8000',
      hasCompany: true,
      companyName: 'Стоянов Строителство',
      isActive: true,
    },
    // Additional Architects
    {
      firstName: 'Архитект Петя',
      lastName: 'Иванова',
      email: 'petya@designstudio.bg',
      phone: '+359888555777',
      address: 'ул. Графа 5, София 1202',
      hasCompany: true,
      companyName: 'Design Studio BG',
      isArchitect: true,
      commissionPercent: 15.0,
      isActive: true,
    },
    {
      firstName: 'Димитър',
      lastName: 'Архитектов',
      email: 'dimitar@modernarchitects.bg',
      phone: '+359899444333',
      address: 'бул. Христо Ботев 112, Пловдив 4002',
      hasCompany: true,
      companyName: 'Modern Architects',
      isArchitect: true,
      commissionPercent: 10.0,
      isActive: true,
    },
    {
      firstName: 'Лора',
      lastName: 'Петкова',
      email: 'lora.petkova@creativespace.bg',
      phone: '+359887222111',
      address: 'ул. Македония 25, Варна 9000',
      hasCompany: true,
      companyName: 'Creative Space',
      isArchitect: true,
      commissionPercent: 8.0,
      isActive: true,
    },
    {
      firstName: 'Владимир',
      lastName: 'Дизайнов',
      email: 'vladimir@interior-design.bg',
      phone: '+359878111999',
      address: 'ул. Ал. Стамболийски 45, Стара Загора 6000',
      hasCompany: false,
      isArchitect: true,
      commissionPercent: 12.5,
      isActive: true,
    },
    {
      firstName: 'Ани',
      lastName: 'Тодорова',
      email: 'ani@luxurydesign.bg',
      phone: '+359899888777',
      address: 'ж.к. Тракия, бл. 150, ап. 25, Пловдив 4004',
      hasCompany: true,
      companyName: 'Luxury Design Studio',
      isArchitect: true,
      commissionPercent: 18.0,
      isActive: true,
    },
    {
      firstName: 'Николай',
      lastName: 'Архитект',
      email: 'nikolay@homespace.bg',
      phone: '+359888333444',
      address: 'ул. Левски 67, Русе 7000',
      hasCompany: true,
      companyName: 'Home Space Design',
      isArchitect: true,
      commissionPercent: 11.0,
      isActive: true,
    },
  ];

  console.log('Creating Clients...');
  const createdClients = [];
  for (const client of clients) {
    // Use eikBulstat for companies or generate one for upsert
    const whereClause = client.hasCompany && client.companyName
      ? { eikBulstat: `EIK${client.firstName.charAt(0)}${client.lastName.charAt(0)}${Date.now()}`.slice(0, 13) }
      : { eikBulstat: `IND${client.firstName.charAt(0)}${client.lastName.charAt(0)}${Date.now()}`.slice(0, 13) };
    
    const clientData = {
      ...client,
      eikBulstat: whereClause.eikBulstat,
    };
    
    const createdClient = await prisma.client.upsert({
      where: whereClause,
      update: clientData,
      create: clientData,
    });
    createdClients.push(createdClient);
  }

  // Create Suppliers (same as manufacturers)
  const suppliers = [
    // Паркет производители
    {
      name: 'foglie_doro',
      displayName: "Foglie d'Oro",
      code: 'FOGLIE',
      website: 'https://fogliedor.it',
      description: 'Италианска луксозна марка за паркет',
      colorCode: '#DAA520',
      isActive: true,
    },
    {
      name: 'salis',
      displayName: 'Salis',
      code: 'SALIS',
      website: 'https://salis.it',
      description: 'Италиански производител на висококачествен паркет',
      colorCode: '#8B4513',
      isActive: true,
    },
    {
      name: 'weitzer',
      displayName: 'Weitzer',
      code: 'WEITZER',
      website: 'https://weitzer.com',
      description: 'Австрийски производител на премиум паркет',
      colorCode: '#2E8B57',
      isActive: true,
    },
    {
      name: 'friulparchet',
      displayName: 'Friulparchet',
      code: 'FRIULPARCHET',
      website: 'https://friulparchet.it',
      description: 'Итало-словенска компания за инженерен паркет',
      colorCode: '#B22222',
      isActive: true,
    },
    {
      name: 'berti',
      displayName: 'Berti',
      code: 'BERTI',
      website: 'https://berti.net',
      description: 'Италиански лидер в производството на паркет',
      colorCode: '#4169E1',
      isActive: true,
    },
    // Врати
    {
      name: 'bluinterni',
      displayName: 'Bluinterni',
      code: 'BLUINTERNI',
      website: 'https://bluinterni.it',
      description: 'Италиански производител на интериорни врати',
      colorCode: '#00008B',
      isActive: true,
    },
    // Мебели
    {
      name: 'arte_brotto',
      displayName: 'Arte Brotto',
      code: 'ARTEBROTTO',
      website: 'https://artebrotto.it',
      description: 'Италиански производител на луксозни мебели',
      colorCode: '#8B4513',
      isActive: true,
    },
    {
      name: 'sicis',
      displayName: 'Sicis',
      code: 'SICIS',
      website: 'https://sicis.com',
      description: 'Итало-словенска компания за декоративни покрития',
      colorCode: '#FFD700',
      isActive: true,
    },
    {
      name: 'talenti',
      displayName: 'Talenti',
      code: 'TALENTI',
      website: 'https://talentisrl.com',
      description: 'Итало-словенски производител на градински мебели',
      colorCode: '#228B22',
      isActive: true,
    },
    {
      name: 'decastelli',
      displayName: 'Decastelli',
      code: 'DECASTELLI',
      website: 'https://decastelli.com',
      description: 'Италиански производител на луксозни мебели',
      colorCode: '#8B008B',
      isActive: true,
    },
    {
      name: 'ravaioli',
      displayName: 'Ravaioli',
      code: 'RAVAIOLI',
      website: 'https://ravaioli.it',
      description: 'Италиански производител на мебели и аксесоари',
      colorCode: '#CD853F',
      isActive: true,
    },
    {
      name: 'uzin',
      displayName: 'Uzin',
      code: 'UZIN',
      website: 'https://uzin.com',
      description: 'Немски производител на лепила и подложки',
      colorCode: '#FF6347',
      isActive: true,
    },
    {
      name: 'parketsense_pro',
      displayName: 'Паркетсенс ПРО',
      code: 'PARKETSENSE',
      website: 'https://parketsense.bg',
      description: 'Българска компания за паркет и подови настилки',
      colorCode: '#32CD32',
      isActive: true,
    },
  ];

  console.log('Creating Suppliers...');
  const createdSuppliers = [];
  for (const supplier of suppliers) {
    const createdSupplier = await prisma.supplier.upsert({
      where: { name: supplier.name },
      update: supplier,
      create: supplier,
    });
    createdSuppliers.push(createdSupplier);
  }

  // Create sample Projects
  const projects = [
    {
      name: 'Апартамент Борисова градина',
      description: 'Ремонт на двустаен апартамент в кв. Борисова градина, София. Включва паркет, врати и мебели.',
      clientId: createdClients[0].id,
      projectType: 'apartment',
      address: 'кв. Борисова градина, София',
      city: 'София',
      status: 'draft',
      totalArea: 65.0,
      roomsCount: 2,
      estimatedBudget: 8500.00,
      startDate: new Date('2024-03-15'),
      expectedCompletionDate: new Date('2024-04-30'),
    },
    {
      name: 'Офис Пловдив',
      description: 'Обзавеждане на нов офис в бизнес сграда в Пловдив. 180 кв.м. площ.',
      clientId: createdClients[1].id,
      projectType: 'office',
      address: 'бул. България 58, Пловдив',
      city: 'Пловдив',
      status: 'active',
      totalArea: 180.0,
      estimatedBudget: 25000.00,
      startDate: new Date('2024-02-01'),
      expectedCompletionDate: new Date('2024-03-15'),
    },
    {
      name: 'Къща Варна',
      description: 'Паркет за цяла къща във Варна. Различни видове дървесина за различните стаи.',
      clientId: createdClients[2].id,
      projectType: 'house',
      address: 'кв. Младост, Варна',
      city: 'Варна',
      status: 'draft',
      totalArea: 120.0,
      roomsCount: 4,
      floorsCount: 2,
      estimatedBudget: 15000.00,
      startDate: new Date('2024-05-01'),
      expectedCompletionDate: new Date('2024-06-30'),
    },
    {
      name: 'Ресторант София Център',
      description: 'Комплексно обзавеждане на ресторант в центъра на София.',
      clientId: createdClients[3].id,
      projectType: 'commercial',
      address: 'ул. Витоша 125, София',
      city: 'София',
      status: 'draft',
      totalArea: 150.0,
      estimatedBudget: 35000.00,
      startDate: new Date('2024-04-15'),
      expectedCompletionDate: new Date('2024-05-30'),
    },
    {
      name: 'Хотел Бургас',
      description: 'Ремонт на хотелски стаи - паркет, врати и мебели за 20 стаи.',
      clientId: createdClients[4].id,
      projectType: 'commercial',
      address: 'морска зона, Бургас',
      city: 'Бургас',
      status: 'archived',
      totalArea: 400.0,
      roomsCount: 20,
      estimatedBudget: 45000.00,
    },
  ];

  console.log('Creating Projects...');
  const createdProjects = [];
  for (const project of projects) {
    const createdProject = await prisma.project.upsert({
      where: { 
        id: `proj_${project.name.toLowerCase().replace(/\s+/g, '_').substring(0, 20)}_${project.clientId.substring(0, 8)}`
      },
      update: { ...project, id: undefined },
      create: {
        ...project,
        id: `proj_${project.name.toLowerCase().replace(/\s+/g, '_').substring(0, 20)}_${project.clientId.substring(0, 8)}`
      },
    });
    createdProjects.push(createdProject);
  }

  console.log('✅ Comprehensive seed completed successfully!');
  console.log('📊 Database Statistics:');
  console.log(`- ProductTypes: ${productTypes.length}`);
  console.log(`- Manufacturers: ${manufacturers.length}`);
  console.log(`- AttributeTypes: ${attributeTypes.length}`);
  console.log(`- AttributeValues: ${attributeValues.length + manufacturerSpecificValues.length}`);
  console.log(`- Sample Products: ${products.length}`);
  console.log(`- Clients: ${clients.length} (включително ${clients.filter(c => c.isArchitect).length} архитекта)`);
  console.log(`- Suppliers: ${suppliers.length}`);
  console.log(`- Projects: ${projects.length}`);
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  }); 